### ISSUE TITLE
GWE-30 Shop Products

### ISSUE THREAD

**Issue by princejoogie** [princejoogie/ground-work-ecom#58] opened 2021-10-21 04:10 UTC
you would also need to add a `status` flag to each product in `AddProduct` which would be of
`type IProductStatus = "ACTIVE" | "OUT_OF_STOCK" | "UNLISTED" | "ARCHIVED"`

![image](https://user-images.githubusercontent.com/47204120/138210111-d86577e9-b984-4462-a826-09956ca198cc.png)

**Comment by joshxfi** [comment] 2021-10-21 04:20
@princejoogie this looks like a duplicate of #23

**Closed** 2021-10-21 04:54 UTC
Labels: duplicate, feature
